version: '3'
services:
  db:
      image: postgres:10-alpine
      environment:
          - POSTGRES_DB=dbsample
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=supersecretpassword
      ports:
          - "6543:5432"

