version: '3'
services:
  db:
    container_name: db
    image: postgres:10-alpine
    environment:
        - POSTGRES_DB=dbumpisa
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=supersecretpassword
    ports:
        - "6543:5432"

